spring.jpa:
    hibernate.ddl-auto: none
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
            format_sql: true
            show_sql: true

spring.sql.init:
    mode: always
    schema-locations: classpath:schema.sql

logging.level:
      org:
          springframework.orm.jpa: INFO
          springframework.transaction: INFO
          springframework.transaction.interceptor: TRACE
          springframework.orm.jpa.JpaTransactionManager: DEBUG
      ru.practicum.shareit: INFO

---
spring:
  datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/${db.name}
        username: postgres
        password: iamroot
  config:
    activate:
      on-profile: dev
db.name: shareit

---
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:shareit2
    username: test
    password: test
  config:
    activate:
      on-profile: ci,test
  sql:
   init:
     mode: always